export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "catgories/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "catgories/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "catgories/FETCH_CATEGORIES_FAILED",
};
